"""Relacion muchos a muchos historia_clinica <-> Cie10

Revision ID: f7acf064f54c
Revises: 
Create Date: 2025-06-11 17:31:45.467395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7acf064f54c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cie10', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capitulo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('grupo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('historia_clinica', schema=None) as batch_op:
        batch_op.drop_column('diagnostico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historia_clinica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostico', mysql.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('cie10', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('activo')
        batch_op.drop_column('grupo')
        batch_op.drop_column('capitulo')

    # ### end Alembic commands ###
